---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: remove-vm-test-1-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: remove-vm
  extra_vars: {
   "vm_name": "vm-test-1"
}